[INFO] 2019-01-13 01:01:46,155 >>	[START]  Processor.preprocess()
[INFO] 2019-01-13 01:01:46,156 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 01:01:46,184 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-01-13 01:01:46,185 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 01:01:46,202 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-01-13 01:01:46,204 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 01:01:46,223 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-01-13 01:01:46,224 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 01:01:46,242 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-01-13 01:01:46,243 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 01:01:46,259 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-01-13 01:01:46,260 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 01:01:46,278 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-01-13 01:01:46,280 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 01:01:46,297 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-01-13 01:01:46,298 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 01:01:46,316 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-01-13 01:01:46,318 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 01:01:46,334 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-01-13 01:01:46,335 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 01:01:46,351 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-01-13 01:01:46,352 >>	[FINISH] Processor.preprocess(): [elapsed_time] >> 00:00:00
[ERROR] 2019-01-13 01:01:46,478 >>	Unexpected Exception Occurred.
Traceback (most recent call last):
  File "src/main.py", line 20, in <module>
    main(get_option())
  File "src/main.py", line 12, in main
    ProcessorFactory.process(args)
  File "/home/icebee/project/Malware/src/processor_factory.py", line 32, in process
    validity, predict = processor.process()
  File "/home/icebee/project/Malware/src/processor.py", line 35, in process
    assert False
AssertionError
