[INFO] 2019-02-14 15:06:21,809 >>	Classifier Type: PYTROCH
[INFO] 2019-02-14 15:06:22,171 >>	Input Path: /home/berry/Malware/data/subset/lgbm_adv
[INFO] 2019-02-14 15:06:22,517 >>	--------------------------------
[ERROR] 2019-02-14 15:06:23,184 >>	Unexpected Exception Occurred.
Traceback (most recent call last):
  File "src/main.py", line 23, in <module>
    main(get_option())
  File "src/main.py", line 14, in main
    ProcessorFactory.process(args)
  File "/home/berry/Malware/src/processor_factory.py", line 37, in process
    ClassifierType.parseType(clf_type),
  File "/home/berry/Malware/src/classifier_type.py", line 20, in parseType
    raise Exception("Error: Please input valid classifier in json")
Exception: Error: Please input valid classifier in json
